### PR TITLE
QQ_Fn for VAST: plot for each category

### PR DESCRIPTION
**Pull request by zeroyin**
I added a `QQ_Fn()` to `VAST`. The function loops through each category (user specified) and applies `SpatialDeltaGLMM::QQ_Fn` to make plots. `ObsModel` is changed to `ObsModel_ez` everywhere. I have only checked for a simple case which I have result data: a multi-species model but homogeneously with `ObsModel=c(2,0)`. Also, please regenerate the document to export this function.

### CODE REVIEW

**Comment by James-Thorson** [comment]
Are you willing to spend a bit more time to confirm that it also works for SpatialDeltaGLMM for a single species model?  You could use the tutorial Rmd there to check, and it will likely require some extra code to check.  This is the strategy I have followed throughout development (to have plotting functions that work across the full set of FishStats tools, SpatialDeltaGLMM, VAST, and MIST, although I don't maintain MIST as well so I'm not gonna ask for that to be checked ;)

**Comment by zeroyin** [comment]
This function only works for VAST and not SpatialDeltaGLMM because I thought VAST would be the main package that integrates the full set of models including for example, both single/multi-species models etc. If you would like to keep all plotting functions in SpatialDeltaGLMM I can modified `SpatialDeltaGLMM::QQ_Fn` instead of opening this new function `VAST::QQ_Fn`. I will do that in a few days.

**Comment by James-Thorson** [comment]
OK, that would be great.  The intent is to have the plotting functions work regardless of which specific model objects are being used, so that users can switch between SpatialDeltaGLMM/VAST/MIST and still use the same plotting/analysis functions

**Comment by zeroyin** [comment]
Hey I am starting to add support for other packages/versions and I found that you now have this e_i (error distribution indicator) besides c_i (category indicator). My question is, for the diagnostic plots, do you think I should still group by categories? Or by error distribution, where homogeneous categories are aggregated? I kind of prefer the former but the latter does make more sense.

**Comment by James-Thorson** [comment]
Yeah, this is why I never went down this path ;)

I could imagine grouping by either error distribution e_i, year t_i, or category c_i, or some factorial cross of these.  Maybe just try c_i for now given that this was your original plan, and I'll look it over then to make sure it doesn't conflict with the original intent of QQ_Fn.

**Comment by zeroyin** [comment]
Please see the pull request in SpatialDeltaGLMM.

**Comment by James-Thorson** [comment]
John Wallace reported a problem with the new QQ_Fn code for version 4.0.0. are you interested in taking a look or would you prefer I do so?

**Comment by zeroyin** [comment]
I will check it. Thx

**Comment by zeroyin** [comment]
Where is the reported issue? Btw I fixed a small bug and changed the code a bit but forgot to pull request so I will fix the new one and submit the final changes.

**Comment by James-Thorson** [comment]
John

Could you share the reproducible exampke of the QQ problem with Yihao, who
made the latest commit to this function?

**Pull request closed without merging**
